### ISSUE TITLE
Bug conocido de recycler view en modo producción

### ISSUE THREAD

**Issue by figonzal1** [figonzal1/LastQuakeChile#10]
## Datos usuario:
![datos_user](https://user-images.githubusercontent.com/46515974/58071998-4cff6080-7b6c-11e9-897f-20a2cdf7cb7b.PNG)

## Error encontrado:
`Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{8bdde10 position=8 id=8, oldPos=-1, pLpos:-1 no parent} android.support.v7.widget.RecyclerView{24566ec VFED..... .F...... 0,366-720,1048 #7f0800ea app:id/recycle_view}, adapter:qk@2b1e94b, layout:android.support.v7.widget.LinearLayoutManager@5d75f28, context:cl.figonzal.lastquakechile.views.MainActivity@fd8d43f
       at android.support.v7.widget.RecyclerView$Recycler.clear(RecyclerView.java)
       at android.support.v7.widget.RecyclerView$Recycler.clear(RecyclerView.java)
       at android.support.v7.widget.GapWorker.add(GapWorker.java)
       at android.support.v7.widget.GapWorker.add(GapWorker.java)
       at android.support.v7.widget.GapWorker.remove(GapWorker.java)
       at android.support.v7.widget.GapWorker.add(GapWorker.java)
       at android.support.v7.widget.GapWorker.run(GapWorker.java)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5659)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)`

## Log del usuario: 
[Error.log](https://github.com/figonzal1/LastQuakeChile/files/3200977/cl.figonzal.lastquakechile_issue_5ce28ec4f8b88c296369876e_crash_session_5CE28E6900B000017AD9909848FEBA6D_DNE_0_v2.log)

**Comment by figonzal1** [comment]
### Solucion encontrada
Solución que solo esconde el problema, se produce cuando un usuario escrolea muy rápido en un dispositivo con poca memoria RAM.
## Código implementado
@Override
	public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {

		try {
			super.onLayoutChildren(recycler, state);
		} catch (IndexOutOfBoundsException e) {
			Log.e("RECYCLER VIEW", "OUT INDEX BUG");
			Crashlytics.log(Log.DEBUG, "RECYCLER VIEW", "OUT INDEX BUG");
		}
	}

**Comment by figonzal1** [comment]
### [Actualización]
#### En vez de:
```
mainList.clear();
...
mainList.add() or mainList.addAll()
...
notifyDataSetChanged();
```
#### Escribir:
```
List res = new ArrayList();
…..
res.add();  //add item or modify list
….
mainList = res;
notifyDataSetChanged();
```
