### ISSUE TITLE
Bug SharedPreference CardView Informativo

### ISSUE THREAD

**Issue by figonzal1** [figonzal1/LastQuakeChile#11]
## Datos usuario:
![asdasd](https://user-images.githubusercontent.com/46515974/58672523-58dde600-8315-11e9-8374-0c27697e137c.PNG)

## Funcionalidad comprometida
![Screenshot_20190530-200752_LastQuakeChile](https://user-images.githubusercontent.com/46515974/58672892-07cef180-8317-11e9-8040-0c61422ef442.jpg)

## Error encontrado:
`Caused by java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
       at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:263)
       at cl.figonzal.lastquakechile.views.QuakeFragment.showCardViewInformation(QuakeFragment.java)
       at cl.figonzal.lastquakechile.views.QuakeFragment.newInstance(QuakeFragment.java)
       at androidx.fragment.app.Fragment.getLifecycle(Fragment.java)
       at androidx.fragment.app.FragmentManagerImpl.ensureInflatedFragmentView(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentController.createController(FragmentController.java)
       at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java)
       at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
       at androidx.appcompat.app.AppCompatDelegateImpl.onPostCreate(AppCompatDelegateImpl.java)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java)
       at cl.figonzal.lastquakechile.views.MainActivity.onCreate(MainActivity.java)
       at android.app.Activity.performCreate(Activity.java:6772)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2715)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2823)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6349)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)`

## Log del usuario: 
[error.log](https://github.com/figonzal1/LastQuakeChile/files/3239138/error.log)

**Comment by figonzal1** [comment]
### [Posible solución]
**Vía desarrollo no existe solución**, usuario final debe reinstalar la aplicación para que el nombre de la llave de shared preference no colisione entre diferentes apk's

**Comment by figonzal1** [comment]
### [Actualización]
Error se corrige en este [commit](https://github.com/figonzal1/LastQuakeChile/commit/2f643995e46998d28affad6a5a412c12775de055)

Se determinó que existía un conflicto de nombre en versiones antiguas (1.1.0), donde la variable **estado de cardview** se almacenaba como _String_ y luevo en la versión 1.2.0 se almacena como _Bool_, provocando dicho error.

Se determina crear un nuevo nombre para la variable (Strings.xml), de esta manera no generará conflictos.
